-- NOOB — 36 more Live Profile Picture presets (NOOB Pro perk), on top of the 64 that exist already. Purely additive: existing presets,
-- and anyone's already-applied live avatar, are completely untouched. This batch is all abstract, colourful, premium-looking optical
-- illusions (kaleidoscopes, moiré, hypnotic spirals, glitch, iridescent liquid, impossible shapes) rather than icon-style pictures, so
-- it does not repeat the look of the earlier 64. The new .svg files ship with the website (public/live-avatars/).
insert into public.live_avatar_presets (id, name, url, sort) values
  ('moire_rings', 'Moiré Rings', '/live-avatars/moire-rings.svg', 65),
  ('kaleidoscope_bloom', 'Kaleidoscope Bloom', '/live-avatars/kaleidoscope-bloom.svg', 66),
  ('hypno_spiral', 'Hypno Spiral', '/live-avatars/hypno-spiral.svg', 67),
  ('rgb_glitch_pulse', 'RGB Glitch Pulse', '/live-avatars/rgb-glitch-pulse.svg', 68),
  ('liquid_chrome_morph', 'Liquid Chrome Morph', '/live-avatars/liquid-chrome-morph.svg', 69),
  ('oil_slick_swirl', 'Oil Slick Swirl', '/live-avatars/oil-slick-swirl.svg', 70),
  ('prism_refraction', 'Prism Refraction', '/live-avatars/prism-refraction.svg', 71),
  ('infinity_tunnel', 'Infinity Tunnel', '/live-avatars/infinity-tunnel.svg', 72),
  ('op_art_waves', 'Op Art Waves', '/live-avatars/op-art-waves.svg', 73),
  ('color_wheel_pinwheel', 'Color Wheel Pinwheel', '/live-avatars/color-wheel-pinwheel.svg', 74),
  ('tie_dye_bloom', 'Tie-Dye Bloom', '/live-avatars/tie-dye-bloom.svg', 75),
  ('mobius_ribbon', 'Möbius Ribbon', '/live-avatars/mobius-ribbon.svg', 76),
  ('holographic_facets', 'Holographic Facets', '/live-avatars/holographic-facets.svg', 77),
  ('vortex_spin', 'Vortex Spin', '/live-avatars/vortex-spin.svg', 78),
  ('impossible_tribar', 'Impossible Tribar', '/live-avatars/impossible-tribar.svg', 79),
  ('checkerboard_illusion', 'Checkerboard Illusion', '/live-avatars/checkerboard-illusion.svg', 80),
  ('chromatic_starburst', 'Chromatic Starburst', '/live-avatars/chromatic-starburst.svg', 81),
  ('barber_pole_twist', 'Barber Pole Twist', '/live-avatars/barber-pole-twist.svg', 82),
  ('mandala_kaleidoscope', 'Mandala Kaleidoscope', '/live-avatars/mandala-kaleidoscope.svg', 83),
  ('glitch_shift', 'Glitch Shift', '/live-avatars/glitch-shift.svg', 84),
  ('soap_bubble_film', 'Soap Bubble Film', '/live-avatars/soap-bubble-film.svg', 85),
  ('spiral_triangles', 'Spiral Triangles', '/live-avatars/spiral-triangles.svg', 86),
  ('hex_tunnel', 'Hex Tunnel', '/live-avatars/hex-tunnel.svg', 87),
  ('paisley_swirl', 'Paisley Swirl', '/live-avatars/paisley-swirl.svg', 88),
  ('ribbon_twist', 'Ribbon Twist', '/live-avatars/ribbon-twist.svg', 89),
  ('scale_shimmer', 'Scale Shimmer', '/live-avatars/scale-shimmer.svg', 90),
  ('diamond_grid_shimmer', 'Diamond Grid Shimmer', '/live-avatars/diamond-grid-shimmer.svg', 91),
  ('concentric_illusion', 'Concentric Illusion', '/live-avatars/concentric-illusion.svg', 92),
  ('crystal_facet_burst', 'Crystal Facet Burst', '/live-avatars/crystal-facet-burst.svg', 93),
  ('spectrum_wave', 'Spectrum Wave', '/live-avatars/spectrum-wave.svg', 94),
  ('fractal_bloom', 'Fractal Bloom', '/live-avatars/fractal-bloom.svg', 95),
  ('zoetrope_spin', 'Zoetrope Spin', '/live-avatars/zoetrope-spin.svg', 96),
  ('color_cycle_orb', 'Color Cycle Orb', '/live-avatars/color-cycle-orb.svg', 97),
  ('tunnel_vision', 'Tunnel Vision', '/live-avatars/tunnel-vision.svg', 98),
  ('color_shift_blob', 'Color Shift Blob', '/live-avatars/color-shift-blob.svg', 99),
  ('illusion_cube', 'Illusion Cube', '/live-avatars/illusion-cube.svg', 100)
on conflict (id) do nothing;
