-- Expands the Guess the Song pool well past 100 tracks, spanning English, Hindi and phonk — the
-- game only had 8 before (all English). Every single video ID below was looked up live against
-- YouTube's own search and verified against its oEmbed endpoint (exists, embeddable, real title)
-- before being written here — none of this is guessed from memory. Picked from official
-- artist/label/VEVO channels (or YouTube's auto-generated "<Artist> - Topic" channels) wherever
-- possible, and skipped anything that looked like a reupload, mix/compilation, or meme edit, since
-- the 4 multiple-choice options need to be real, guessable song titles.
insert into public.song_guess_tracks (title, artist, audio_url, youtube_video_id, clip_start_seconds, clip_length_seconds)
select v.title, v.artist, '', v.yt, 30, 10
from (values
  -- English
  ('Perfect', 'Ed Sheeran', '2Vv-BfVoq4g'),
  ('Thinking Out Loud', 'Ed Sheeran', 'lp-EO5I60KA'),
  ('Rolling in the Deep', 'Adele', 'rYEDA3JcQqw'),
  ('Hello', 'Adele', 'YQHsXMglC9A'),
  ('Someone Like You', 'Adele', 'hLQl3WQQoQ0'),
  ('Blank Space', 'Taylor Swift', 'e-ORhEE9VVg'),
  ('Love Story', 'Taylor Swift', '8xg3vE8Ie_E'),
  ('Sorry', 'Justin Bieber', 'fRh_vgS2dFE'),
  ('Baby', 'Justin Bieber ft. Ludacris', 'kffacxfA7G4'),
  ('Sugar', 'Maroon 5', '09R8_2nJtjg'),
  ('Girls Like You', 'Maroon 5 ft. Cardi B', 'aJOTlE1K90k'),
  ('Roar', 'Katy Perry', 'CevxZvSJLk8'),
  ('Firework', 'Katy Perry', 'QGJuMBdaqIw'),
  ('Radioactive', 'Imagine Dragons', 'ktvTqknDobU'),
  ('Levitating', 'Dua Lipa', 'TUVcZfQe-Kw'),
  ('Don''t Start Now', 'Dua Lipa', 'oygrmJFKYZY'),
  ('bad guy', 'Billie Eilish', 'DyDfgMOUjCI'),
  ('thank u, next', 'Ariana Grande', 'gl1aHhXnN1k'),
  ('7 rings', 'Ariana Grande', 'QYh6mYIJG2Y'),
  ('Hymn for the Weekend', 'Coldplay', 'YykjpeuMNEk'),
  ('Viva la Vida', 'Coldplay', 'dvgZkm1xWPE'),
  ('24K Magic', 'Bruno Mars', 'UqyT8IEBkvY'),
  ('That''s What I Like', 'Bruno Mars', 'PMivT7MJ41M'),
  ('Counting Stars', 'OneRepublic', 'hT_nvWreIhg'),
  ('See You Again', 'Wiz Khalifa ft. Charlie Puth', 'RgKAFK5djSk'),
  ('Stitches', 'Shawn Mendes', 'VbfpW0pbvaU'),
  ('Chandelier', 'Sia', '2vjPBrBU-TM'),
  ('Wake Me Up', 'Avicii', 'IcrbM1l_BoI'),
  ('Faded', 'Alan Walker', '60ItHLz5WEA'),
  ('This Is What You Came For', 'Calvin Harris ft. Rihanna', 'kOkQ4T5WO9E'),
  ('Circles', 'Post Malone', 'wXhTHyIgQ_U'),
  ('Sunflower', 'Post Malone & Swae Lee', 'ApXoWvfEYVU'),
  ('Shallow', 'Lady Gaga & Bradley Cooper', 'bo_efYhYU2A'),
  ('Someone You Loved', 'Lewis Capaldi', 'zABLecsR5UE'),
  ('As It Was', 'Harry Styles', 'H5v3kku4y6Q'),
  ('drivers license', 'Olivia Rodrigo', 'ZmDBbnmKpqQ'),
  ('Flowers', 'Miley Cyrus', 'G7KNmW9a75Y'),
  ('Closer', 'The Chainsmokers ft. Halsey', '0zGcUoRlhmw'),
  ('Umbrella', 'Rihanna ft. Jay-Z', 'CvBfHwUxHIk'),
  ('Lose Yourself', 'Eminem', 'xFYQQPAOz7Y'),
  ('Love Me Like You Do', 'Ellie Goulding', 'AJtDXIazrMo'),
  ('Havana', 'Camila Cabello ft. Young Thug', 'BQ0mxQXmLsk'),
  ('Numb', 'Linkin Park', 'kXYiU_JCYtU'),
  ('Yellow', 'Coldplay', 'yKNxeF4KMsY'),
  ('I Want It That Way', 'Backstreet Boys', '4fndeDfaWCg'),
  ('It''s My Life', 'Bon Jovi', 'vx2u5uUu3DE'),
  ('Billie Jean', 'Michael Jackson', 'Zi_XLOBDo_Y'),

  -- Hindi
  ('Tum Hi Ho', 'Arijit Singh', '81qmmlsIE3k'),
  ('Channa Mereya', 'Arijit Singh', '284Ov7ysmfA'),
  ('Kesariya', 'Arijit Singh', 'BddP6PYo2gs'),
  ('Raataan Lambiyan', 'Tanishk Bagchi, Jubin Nautiyal, Asees Kaur', 'GLGuLXKT9Ng'),
  ('Tera Ban Jaunga', 'Tulsi Kumar, Akhil Sachdeva', 'Qdz5n1Xe5Qo'),
  ('Tum Se Hi', 'Mohit Chauhan', 'mt9xg0mmt28'),
  ('Agar Tum Saath Ho', 'Alka Yagnik, Arijit Singh', '6SGRn9OHtFY'),
  ('Kar Gayi Chull', 'Badshah, Fazilpuria', 'NTHz9ephYTw'),
  ('Gerua', 'Arijit Singh, Antara Mitra', 'AEIVhBS6baE'),
  ('Humdard', 'Arijit Singh', 'FJ55SHCzt88'),
  ('Janam Janam', 'Arijit Singh, Antara Mitra', 'pIBoAh4OXhQ'),
  ('Soch Na Sake', 'Arijit Singh, Tulsi Kumar', 'MRtRcTfszjY'),
  ('Bolna', 'Arijit Singh, Asees Kaur', 'AJ-7X6cvOhY'),
  ('Galliyan', 'Ankit Tiwari', 'FxAG_11PzCk'),
  ('Chaiyya Chaiyya', 'Sukhwinder Singh, Sapna Awasthi', 'K-pX4qwtAxA'),
  ('Tujhe Kitna Chahne Lage', 'Arijit Singh', 'AgX2II9si7w'),
  ('Tum Hi Aana', 'Jubin Nautiyal', 'RemShT6JAHw'),
  ('Dilbar', 'Neha Kakkar, Dhvani Bhanushali', 'TRa9IMvccjg'),
  ('Apna Bana Le', 'Arijit Singh', 'UEvOsQBu1jY'),
  ('Kabira', 'Tochi Raina, Rekha Bhardwaj', 'jHNNMj5bNQw'),
  ('Ilahi', 'Arijit Singh', 'fdubeMFwuGs'),
  ('Badtameez Dil', 'Benny Dayal', 'II2EO3Nw4m0'),
  ('Tune Maari Entriyaan', 'Vishal Dadlani', '2I3NgxDAiqE'),
  ('Zaalima', 'Arijit Singh, Harshdeep Kaur', 'lpdRqn6xwiM'),
  ('Tera Yaar Hoon Main', 'Arijit Singh, Rochak Kohli', 'EatzcaVJRMs'),
  ('Tum Jo Aaye', 'Rahat Fateh Ali Khan, Tulsi Kumar', 'y2O44HDZWws'),
  ('Enna Sona', 'Arijit Singh', 'mrdRHsIkK_c'),
  ('Tujhe Dekha To', 'Lata Mangeshkar, Kumar Sanu', 'cNV5hLSa9H8'),
  ('Kal Ho Naa Ho', 'Sonu Nigam', 'g0eO74UmRBs'),
  ('Hawayein', 'Arijit Singh', 'lBACSadCKaQ'),
  ('Phir Bhi Tumko Chaahunga', 'Arijit Singh', 'jQdDpRTVe9k'),
  ('Mast Magan', 'Arijit Singh', 'xitd9mEZIHk'),
  ('Dil Diyan Gallan', 'Atif Aslam', 'SAcpESN_Fk4'),
  ('Khairiyat', 'Arijit Singh', 'hoNb6HuNmU0'),
  ('Bekhayali', 'Sachet Tandon', 'VOLKJJvfAbg'),
  ('Shayad', 'Arijit Singh', 'MJyKN-8UncM'),
  ('Pal Pal Dil Ke Paas', 'Arijit Singh', 'lgTHGZF3BQw'),
  ('Raabta', 'Pritam, Arijit Singh', 'zAU_rsoS5ok'),
  ('Jeene Laga Hoon', 'Atif Aslam, Shreya Ghoshal', 'pkzOBl1p7y4'),
  ('O Re Piya', 'Rahat Fateh Ali Khan', 'iv7lcUkFVSc'),
  ('Saibo', 'Shreya Ghoshal, Tochi Raina', 'GtNrQy90Ih4'),
  ('Tum Ho', 'Mohit Chauhan', 'Wa8dQ_5Kmn0'),
  ('Phir Le Aya Dil', 'Arijit Singh', 'k6BnSIs3XUQ'),
  ('Kuch Kuch Hota Hai', 'Udit Narayan, Alka Yagnik', 'bKZTnnFU9HA'),
  ('Chura Liya Hai Tumne', 'Mohammed Rafi, Asha Bhosle', 'seFeZOgyFsc'),
  ('Mere Haath Mein', 'Sonu Nigam, Sunidhi Chauhan', 'qtz5mpvgAM0'),
  ('Yeh Dosti', 'Kishore Kumar, Manna Dey', '1T8G_d5o5Gs'),
  ('Tujh Mein Rab Dikhta Hai', 'Roop Kumar Rathod', 'qoq8B8ThgEM'),
  ('Tum Hi Ho Bandhu', 'Arijit Singh, Shalmali Kholgade', 'o1RducJbUdc'),
  ('Iktara', 'Kavita Seth, Amitabh Bhattacharya', 'akjdj6iHttY'),
  ('Khuda Jaane', 'KK, Shilpa Rao', 'cmMiyZaSELo'),
  ('Tujhe Bhula Diya', 'Mohit Chauhan, Shafqat Amanat Ali', '-Hb2DeHvvEg'),
  ('Nagada Sang Dhol', 'Shreya Ghoshal, Osman Mir', '3X7x4Ye-tqo'),

  -- Phonk
  ('Murder In My Mind', 'Kordhell', 'w-sQRS-Lc9k'),
  ('Live Another Day', 'Kordhell', '7pmUQJ5KAlU'),
  ('Close Eyes', 'DVRST', 'ao4RCon11eY'),
  ('I''m Sorry', 'DVRST', 'bsO5G0cY9bc'),
  ('Metamorphosis', 'Interworld', 'lJvRohYSrZM'),
  ('GigaChad Theme (Phonk House Version)', 'g3ox_em', 'OVh0bMNSFss'),
  ('Nunchuk', 'Saint PHNX', 'VorOcoIZWvk'),
  ('Nightcrawler', 'Phonk Playa', 'plSMPxF6onA'),
  ('Disaster', 'KSLV', 'rOgwAIn_zcY'),
  ('Astronaut In The Ocean', 'Masked Wolf', 'MEg-oqI9qmw'),
  ('Cradles', 'Sub Urban', 'KBtk5FUeJbk'),
  ('Moonlight', 'XXXTENTACION', 'GX8Hg6kWQYI'),
  ('Lithe', 'Pyrokinesis', 'E44ucXwZlcU'),
  ('Ascend', 'Dxrk ダーク', 'rd09ya6RIrY'),
  ('My Head Is Spinnin''', 'DJ Squeeky & Mack Daddy Ju', 'wRoc_Il8QfA'),
  ('No Batidão (Slowed)', 'ZXKAI', 'zeKCzmAKKP4'),
  ('Baixo', 'xxanteria', 'MEz6cl2z8GU'),
  ('Yummi', 'LXNGVX', '-EJtyQtY2tU')
) as v(title, artist, yt)
where not exists (select 1 from public.song_guess_tracks t where t.youtube_video_id = v.yt);
