-- NOOB — 30 more Live Profile Picture presets (NOOB Pro perk), on top of the original 34. Purely additive: existing presets, and
-- anyone's already-applied live avatar, are completely untouched. The new .svg files ship with the website (public/live-avatars/).
insert into public.live_avatar_presets (id, name, url, sort) values
  ('lightning_storm', 'Lightning Storm', '/live-avatars/lightning-storm.svg', 35),
  ('dragon_eye', 'Dragon Eye', '/live-avatars/dragon-eye.svg', 36),
  ('lava_flow', 'Lava Flow', '/live-avatars/lava-flow.svg', 37),
  ('snowflake_spin', 'Snowflake Spin', '/live-avatars/snowflake-spin.svg', 38),
  ('cyber_grid', 'Cyber Grid', '/live-avatars/cyber-grid.svg', 39),
  ('disco_ball', 'Disco Ball', '/live-avatars/disco-ball.svg', 40),
  ('vinyl_spin', 'Vinyl Spin', '/live-avatars/vinyl-spin.svg', 41),
  ('compass_spin', 'Compass Spin', '/live-avatars/compass-spin.svg', 42),
  ('shooting_star', 'Shooting Star', '/live-avatars/shooting-star.svg', 43),
  ('coral_reef', 'Coral Reef', '/live-avatars/coral-reef.svg', 44),
  ('volcano_glow', 'Volcano Glow', '/live-avatars/volcano-glow.svg', 45),
  ('owl_eyes', 'Owl Eyes', '/live-avatars/owl-eyes.svg', 46),
  ('wolf_howl', 'Wolf Howl', '/live-avatars/wolf-howl.svg', 47),
  ('cat_eyes', 'Cat Eyes', '/live-avatars/cat-eyes.svg', 48),
  ('tiger_stripes', 'Tiger Stripes', '/live-avatars/tiger-stripes.svg', 49),
  ('panda_bamboo', 'Panda Bamboo', '/live-avatars/panda-bamboo.svg', 50),
  ('unicorn_horn', 'Unicorn Horn', '/live-avatars/unicorn-horn.svg', 51),
  ('dragonfly_wings', 'Dragonfly Wings', '/live-avatars/dragonfly-wings.svg', 52),
  ('jellyfish_glow', 'Jellyfish Glow', '/live-avatars/jellyfish-glow.svg', 53),
  ('koi_swirl', 'Koi Swirl', '/live-avatars/koi-swirl.svg', 54),
  ('sakura_bloom', 'Sakura Bloom', '/live-avatars/sakura-bloom.svg', 55),
  ('maple_swirl', 'Maple Swirl', '/live-avatars/maple-swirl.svg', 56),
  ('robot_scan', 'Robot Scan', '/live-avatars/robot-scan.svg', 57),
  ('cassette_spin', 'Cassette Spin', '/live-avatars/cassette-spin.svg', 58),
  ('rocket_launch', 'Rocket Launch', '/live-avatars/rocket-launch.svg', 59),
  ('satellite_orbit', 'Satellite Orbit', '/live-avatars/satellite-orbit.svg', 60),
  ('ufo_beam', 'UFO Beam', '/live-avatars/ufo-beam.svg', 61),
  ('meteor_shower', 'Meteor Shower', '/live-avatars/meteor-shower.svg', 62),
  ('black_hole', 'Black Hole', '/live-avatars/black-hole.svg', 63),
  ('solar_flare', 'Solar Flare', '/live-avatars/solar-flare.svg', 64)
on conflict (id) do nothing;
